[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "joyous-departures"
version = "0.1.0"
description = "Generate warm, heartfelt goodbye messages for email templates"
readme = "../../README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "siviter.xyz" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Homepage = "https://github.com/siviter-xyz/joyous-departures"
Repository = "https://github.com/siviter-xyz/joyous-departures"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "_joyous_departures"

